# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1669b04a992f552909e5e5f81dd31b6f8c93848d8dd871d378a119bbd5da9fc3c138124bf5791bd0ad8de7d29445a3498a428e6d58fb328f8e571f50157cef7

test:
  secret_key_base: fab0d2465acc219e56d4f20b7d6f42c2e5bfe6dc32efc8ee3c4f17a2d884605eb7acdd85407b81263ec51b283b27c6de8e3bc73c31f59a4373120f95f689fb9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
